---
title:    "Latent Gender Score"
subtitle: "Process Data: Fit SEM and GDM"
author:   "Charité - Universitätsmedizin Berlin, Institut für Public Health\n\n
           Hans-Aloys Wischmann, Mascha Kern"
date:     "** **\n\n
           Revised:  March 27, 2026\n\n
           Executed: `r format(Sys.time(), '%B %d, %Y')`"
output:   "word_document"
---

```{r setup, include = FALSE}
  start.time <- Sys.time()
  source("./Common.R")
```
## Load: Preprocessed Data

```{r load_preprocessed}
  load(file = data_prep_file)

  # append hourly_wage, append scaled age (unit increment equals +10 years), normalize weights
  df_all <- complete(df_analysis, action = "long", include = TRUE) %>%
    mutate(age_10y = 0.1 * age, gross_hourly_wage = current_monthly_gross_labor_income / (4.35 * work_time)) %>%
    mutate(across(c(current_monthly_gross_labor_income, gross_hourly_wage), ~((.x - median(.x, na.rm = TRUE)) / IQR(.x, na.rm = TRUE)))) %>%
    group_by(.imp) %>% mutate(weight_factor = n() * weight_factor / sum(weight_factor, na.rm = TRUE)) %>% ungroup()

  # continuous dataset with factors converted to integer data
  df_con <- df_all %>% mutate(across(!age_group & where(is.factor), ~as.integer(as.character(.x))))

  # single frames of all imputed datasets, continuous and with factors
  df_cmp <- df_con %>% filter(.imp != 0) # continuous
  df_gdm <- df_all %>% filter(.imp != 0) # with factors
```
## SEM: Domain Knowledge Model

```{r read_SEM_GDM_models}
  # read the SEM and GDM models, including layout and nodes
  source(domain_sem_file)
```
## SEM

```{r sem_fit}
  print("SEM Model")
  writeLines(sem_model)
  print("SEM Model without age for stratification by age, without current_mat_parent_leave for 65+")
  writeLines(sem_model_wo_age)
  print("SEM Model without link between sex_binary and gender")
  writeLines(sem_model_sens)

  sem_mi_all <- sem.mi(sem_model,           data = as.mids(df_con), auto.fix.first = FALSE)
  sem_mi_age <- sem.mi(sem_model_wo_age,    data = as.mids(df_con), auto.fix.first = FALSE, group = "age_group")
  sem_mi_wgh <- sem.mi(sem_model,           data = as.mids(df_con), auto.fix.first = FALSE, sampling.weights = "weight_factor",
                                                                                            sampling.weights.normalization = "none",
                                                                                            observed.information = "h1")
  sem_mi_sns <- sem.mi(sem_model_sens,      data = as.mids(df_con), auto.fix.first = FALSE)

  tab_mi_all <- summary(sem_mi_all, ci = TRUE, fit.measures = TRUE, output = "data.frame")
  tab_mi_age <- summary(sem_mi_age, ci = TRUE, fit.measures = TRUE, output = "data.frame")
  tab_mi_wgh <- summary(sem_mi_wgh, ci = TRUE, fit.measures = TRUE, output = "data.frame")
  tab_mi_sns <- summary(sem_mi_sns, ci = TRUE, fit.measures = TRUE, output = "data.frame")

  # check correlations of residuals (main model with multiple imputation)
  # cf. Tips for Inspecting Residuals, Rex B. Kline: Principles and Practice of Structural Equation Modeling
  res_mi_all <- lavResiduals.mi(sem_mi_all, type = "cor")
  as.data.frame(res_mi_all$cov) %>% rownames_to_column("V1") %>%
    pivot_longer(!V1, names_to = "V2", values_to = "Cov") %>% arrange(desc(abs(Cov))) %>%
    filter(abs(Cov) > 0.1, V1 < V2) %>% mutate(Pair = sprintf("%s <-> %s", V1, V2), Cov = sprintf("%.02f", Cov)) %>%
    select(Cov, Pair) %>% 
    flextable() %>% set_caption("SEM (sem.mi, main model) residual (non-model-explained) correlations") %>%
      align(j = 1, align = "right", part = "body") %>% autofit()

  # check correlations of residuals (sensitivity model with multiple imputation)
  # cf. Tips for Inspecting Residuals, Rex B. Kline: Principles and Practice of Structural Equation Modeling
  res_mi_sns <- lavResiduals.mi(sem_mi_sns, type = "cor")
  as.data.frame(res_mi_sns$cov) %>% rownames_to_column("V1") %>%
    pivot_longer(!V1, names_to = "V2", values_to = "Cov") %>% arrange(desc(abs(Cov))) %>%
    filter(abs(Cov) > 0.1, V1 < V2) %>% mutate(Pair = sprintf("%s <-> %s", V1, V2), Cov = sprintf("%.02f", Cov)) %>%
    select(Cov, Pair) %>% 
    flextable() %>% set_caption("SEM (sem.mi, sensitivity model) residual (non-model-explained) correlations") %>%
      align(j = 1, align = "right", part = "body") %>% autofit()
```
## SEM: Outcomes

```{r sem_outcomes}
  # extract outcome coefficients with confidence intervals
  left_join(
    left_join(
      tab_mi_all$pe %>% filter(grepl("incidence", lhs), op == "~") %>%
                mutate(estimate = sprintf("%.3f [%.3f, %.3f]", est, ci.lower, ci.upper)) %>%
                mutate(sig = print_p(pvalue)) %>%
                select(incidence = lhs, predictor = rhs, estimate, sig),
      tab_mi_wgh$pe %>% filter(grepl("incidence", lhs), op == "~") %>%
                mutate(estimate.w = sprintf("%.3f [%.3f, %.3f]", est, ci.lower, ci.upper)) %>%
                mutate(sig.w = print_p(pvalue)) %>%
                select(incidence = lhs, predictor = rhs, estimate.w, sig.w),
      by = c("incidence", "predictor")),
    tab_mi_sns$pe %>% filter(grepl("incidence", lhs), op == "~") %>%
              mutate(estimate.s = sprintf("%.3f [%.3f, %.3f]", est, ci.lower, ci.upper)) %>%
              mutate(sig.s = print_p(pvalue)) %>%
              select(incidence = lhs, predictor = rhs, estimate.s, sig.s),
    by = c("incidence", "predictor")) %>%
    mutate(incidence = gsub("_incidence", "", incidence)) %>%
    flextable() %>% set_caption("SEM (sem.mi) Regressions (unweighted/weighted/sensitivity)") %>%
    hline(i = 9) %>% autofit()
  tab_mi_age$pe %>% filter(grepl("incidence", lhs), op == "~") %>%
    mutate(est = round(est, 3)) %>%
    mutate(group = levels(df_analysis$data$age_group)[group]) %>%
    select(group, outcome = lhs, predictor = rhs, est) %>%
    pivot_wider(names_from = group, values_from = est) %>%
    flextable() %>% set_caption("SEM (sem.mi) Regressions by Age Group, unweighted") %>% autofit() %>%
    hline(i = 8) %>% autofit()

  # Document fit metrics
  all <- tab_mi_all$fit[c("rmsea", "srmr", "aic")] # unweighted
  wgh <- tab_mi_wgh$fit[c("rmsea", "srmr", "aic")] # weighted
  age <- tab_mi_age$fit[c("rmsea", "srmr", "aic")] # age-stratified
  sns <- tab_mi_sns$fit[c("rmsea", "srmr", "aic")] # age-stratified
  cbind(as.data.frame(all), as.data.frame(wgh), as.data.frame(age), as.data.frame(sns)) %>%
    mutate(fit_metric = rownames(.)) %>%
    mutate(fit_metric = str_replace_all(fit_metric,
                                        c("aic"   = "AIC:   Akaike Information Criterion",
                                          "rmsea" = "RMSEA: Root Mean Square Error of Approximation",
                                          "srmr"  = "SRMSR: Standardized Root Mean Square Residual"))) %>%
    select(fit_metric, all, wgh, age, sns) %>%
    mutate(across(!fit_metric, ~round(.x, 3))) %>%
    flextable() %>% set_caption("SEM Models - Fit Info") %>% autofit()
```
## SEM: Gender Statistics and Plots

```{r gender_SEM}
  # plot SEM (for all imputations combined)
  sem_all <- sem(sem_model_sens, data = df_cmp, auto.fix.first = FALSE)
  node_names <- get_nodes(sem_all, label = str_replace_all(name, c("current_" = "", "age_10y" = "age", "_" = "\n")))
  edges <- get_edges(sem_all) %>% mutate(label_location = ifelse(from != "gender", 0.3, 0.5), curvature = ifelse(arrow == "none", 40, curvature))
  sem_plot <- graph_sem(model = sem_all, layout = sem_layout, nodes = node_names, angle = 180.0,
                        text_size = 2.4, rect_width = 1.7, rect_height = 1.5,
                        variance_diameter = NA, fix_coord = TRUE,
                        curvature = 120.0, edges = edges)
  plot_pdf_png("./Results_Plot_SEM_Sensitivity", 1.0, sem_plot)

  # plot SEM (for all imputations combined)
  sem_all <- sem(sem_model, data = df_cmp, auto.fix.first = FALSE)
  node_names <- get_nodes(sem_all, label = str_replace_all(name, c("current_" = "", "age_10y" = "age", "_" = "\n")))
  edges <- get_edges(sem_all) %>% mutate(label_location = ifelse(from != "gender", 0.3, 0.5), curvature = ifelse(arrow == "none", 40, curvature))
  sem_plot <- graph_sem(model = sem_all, layout = sem_layout, nodes = node_names, angle = 180.0,
                        text_size = 2.4, rect_width = 1.7, rect_height = 1.5,
                        variance_diameter = NA, fix_coord = TRUE,
                        curvature = 120.0, edges = edges)
  plot_pdf_png("./Results_Plot_SEM", 1.0, sem_plot)

  # verify that sex_binary and mean gender correlate positively
  df_cmp %>% mutate(gender = lavPredict(sem_all, type = "lv", assemble = TRUE)[,"gender"]) %>%
    group_by(sex_binary) %>% reframe(gender = mean(gender)) %>%
    mutate(sex = ifelse(sex_binary == 0, "Sex_M", "Sex_F")) %>% select(sex, sex_binary, gender) %>%
    flextable() %>% set_caption("SEM: Mean latent gender by sex_binary (main model)") %>% autofit()

  # analyze gender distribution (from sensitivity model by age_group)
  sem_all <- sem(sem_model_wo_age, data = df_cmp, auto.fix.first = FALSE, group = "age_group")
  df_cmp <- df_cmp %>% mutate(gender = lavPredict(sem_all, type = "lv", assemble = TRUE)[,"gender"]) %>%
    mutate(sex_binary = ifelse(sex_binary == 0, "Sex_M", "Sex_F"))

  # provide statistics for latent variable gender stratified by binary sex
  df_cmp %>%
    mutate(age_group = paste("Ages_", age_group, sep = "")) %>%
    group_by(age_group, sex_binary) %>% reframe(mean_gender = round(mean(gender), 3), sd_gender = round(sd(gender), 3)) %>%
    flextable() %>% set_caption("SEM: Mean/SD for latent gender by sex_binary (age group stratified model)") %>% autofit()

  # plot distribution of latent variable gender stratified by binary sex
  plot_pdf_png("./Results_Plot_SEM_Gender_by_Sex", 1.0,
    df_cmp %>%
    mutate(age_group = paste("Ages_", age_group, sep = "")) %>%
    mutate(gender = pmin(pmax(gender, -4), 5)) %>%
    ggplot(aes(x = gender)) + geom_histogram(binwidth = 0.05) +
      labs(x = "Gender (SEM)", y = "Frequency") +
      facet_grid(vars(sex_binary), vars(age_group)))

  # plot distribution of latent variable gender stratified by immigration background
  plot_pdf_png("./Results_Plot_SEM_Gender_by_Sex_by_Immi", 1.0,
    df_cmp %>%
    mutate(immigration_history = paste("Migration_", immigration_history, sep = "")) %>%
    mutate(gender = pmin(pmax(gender, -4), 5)) %>%
    ggplot(aes(x = gender)) + geom_histogram(binwidth = 0.10) +
      labs(x = "Gender (SEM)", y = "Frequency") +
      facet_grid(vars(sex_binary), vars(immigration_history)))
```
## GDM: Fit

```{r GDM}
  print("GDM Model (stratification by age group), common outcomes model (without age)")
  writeLines(gdm_model)
  writeLines(m_dx_wo_age)
  writeLines(s_dx_wo_age)

  # GDM: Benchmark analysis (step one - use predicted probability for binary sex as proxy for gender)
  gdm_age <- df_gdm %>% glm(as.formula(gdm_model), data = ., family = binomial(link = logit))
  df_gdm  <- df_gdm %>% mutate(gender = predict(gdm_age, newdata = ., type = "response"))

  # plot distribution of latent variable gender stratified by binary sex
  plot_pdf_png("./Results_Plot_GDM_Gender_by_Sex", 1.0,
    df_gdm %>%
    mutate(sex_binary = ifelse(sex_binary == 0, "Sex_M", "Sex_F")) %>%
    mutate(age_group = paste("Ages_", age_group, sep = "")) %>%
    ggplot(aes(x = gender)) + geom_histogram(binwidth = 0.05) +
      labs(x = "Gender (GDM)", y = "Frequency") +
      facet_grid(vars(sex_binary), vars(age_group)))

  # GDM (step two), apply regressions across all imputed datasets
  m_dx_f <- as.formula(m_dx_wo_age)
  s_dx_f <- as.formula(s_dx_wo_age)
  rr_with_ci(glm(m_dx_f, data = df_gdm %>% filter(age_group == "[65,Inf)"), family = binomial(link = logit)), "Migraine Incidence, 65+")
  rr_with_ci(glm(m_dx_f, data = df_gdm %>% filter(age_group == "[50,65)"),  family = binomial(link = logit)), "Migraine Incidence, 50-64")
  rr_with_ci(glm(m_dx_f, data = df_gdm %>% filter(age_group == "[35,50)"),  family = binomial(link = logit)), "Migraine Incidence, 35-50")
  rr_with_ci(glm(m_dx_f, data = df_gdm %>% filter(age_group == "[18,35)"),  family = binomial(link = logit)), "Migraine Incidence, 18-35")
  rr_with_ci(glm(s_dx_f, data = df_gdm %>% filter(age_group == "[65,Inf)"), family = binomial(link = logit)), "Stroke Incidence, 65+")
  rr_with_ci(glm(s_dx_f, data = df_gdm %>% filter(age_group == "[50,65)"),  family = binomial(link = logit)), "Stroke Incidence, 50-64")
  rr_with_ci(glm(s_dx_f, data = df_gdm %>% filter(age_group == "[35,50)"),  family = binomial(link = logit)), "Stroke Incidence, 35-50")
  rr_with_ci(glm(s_dx_f, data = df_gdm %>% filter(age_group == "[18,35)"),  family = binomial(link = logit)), "Stroke Incidence, 18-35")
```
## SEM model details

```{r details_and_done}
  tab_mi_all
  tab_mi_age
  tab_mi_wgh
  tab_mi_sns
  print(Sys.time() - start.time)
```